name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.1
  provider: ^6.1.2
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^5.0.0
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  geocoding: ^2.0.5
  firebase_storage: ^12.3.2 
  image_picker: ^1.1.2
  cross_file: ^0.3.4+2
  intl: ^0.19.0
  timeago: ^3.7.0
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - assets/cat_pin.svg